
import { CardData } from "@/types/card";

export const createDefaultCard = (): CardData => ({
  id: Date.now().toString(),
  title: "Modern Card",
  description: "Live preview with real-time updates",
  bgGradientFrom: "#523091",
  bgGradientTo: "#1a0b33",
  bgOpacityFrom: "0.70",
  bgOpacityTo: "0.14",
  shadowColor: "#7c3aed",
  shadowOpacity: "0.3",
  enableHoverEffects: true,
  enableAnimations: true,
  cardWidth: "320",
  cardHeight: "200",
  cardPadding: "24",
  cardBorderRadius: {
    topLeft: "16",
    topRight: "16",
    bottomLeft: "16",
    bottomRight: "16",
    unit: "px",
  },
  cardOpacity: 100,
  shadowSettings: {
    inset: false,
    x: "0",
    y: "30",
    blur: "50",
    spread: "0",
  },
  titleFont: "Inter",
  titleSize: 18,
  titleWeight: "600",
  titleAlign: "left",
  descriptionFont: "Inter",
  descriptionSize: 14,
  descriptionWeight: "400",
  descriptionAlign: "left",
  rotation: 0,
  scaleX: 1,
  scaleY: 1,
  blur: 0,
  brightness: 100,
  contrast: 100,
  saturation: 100,
});
